### PR TITLE
rename camera package and fix policies

### PR DESCRIPTION
**Pull request by StraightDroid**
Change-Id: I2bfc06759ee6fb511c6e9c9228c0de02ec0cde4c

Compiled against original lineageos repositories ...

### CODE REVIEW

**Comment by StraightDroid** [comment]
hopefully I can do it better in the future ...

**Comment by Claymore1297** [comment]
Please use proper commit-messages, and don't mix things up in commits. LOS use snap, not SnapdragonCamera. regards Claymore

**Comment by StraightDroid** [comment]
On my recent built the camera was not included. After some research I found Snapwas renamed to SnapdragonCamera. 
https://github.com/LineageOS/android_packages_apps_Snap

android_packages_apps_Snap/Android.mk

LOCAL_PACKAGE_NAME := SnapdragonCamera

Hope that helps, might be that your source tree isn't updated since (or aicp)

regards StraightDroid

**Comment by Claymore1297** [comment]
this is LOS here, not AICP. LOS snap seems to be rebased and have much open commits. see topic "pie-snap", which rename the package again to Snap.

**Comment by StraightDroid** [comment]
hm. I'm on hold now. Not sure if I can do it again ... the step back to pure aosp. Allready done for evo3d 4 years ago.Would like to look at the base what I'm can do for you on the hardware level. In many little situation (android car, bluetooth and sim) the mobile get unstable.  If I'm fail .. i come back to lineageos.

I have to confess (my personal opinion) with the repopick. It is always unclear if they will ever be incorporated. But thanks for the hint. 

Have a nice day.

StraightDroid

**Pull request closed without merging**
